name: Terraform Destroy Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    defaults:
      run:
        working-directory: module
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: v1.5.6

      - name: Initialize Terraform
        run: terraform init
        working-directory: module

      - name: Plan Terraform Changes
        run: terraform plan -var-file="manish.tfvars"
        working-directory: module
       
      - name: Destroy Terraform Resources (Optional)
        run: terraform destroy -var-file="manish.tfvars" -auto-approve
        working-directory: module
        

